
component_list = [
    '01_clickable_title_ctrl',
    '02_description_ctrl',
    '04_partition_run_select_ctrl',
    '05_file_select_ctrl',
    '06_trigger_record_select_ctrl',
    '07_refresh_ctrl',
    '23_apa_select_ctrl',
    '08_adc_map_selection_ctrl',
    '09_colorscale_ctrl',
    '10_tr_colour_range_slider_ctrl',
    '11_range_slider_pos_ctrl',
    '12_static_image_ctrl',
    '13_fft_phase_fmin_fmax_ctrl',
    '14_density_plot_ctrl',
    '16_channel_number_ctrl',
    '17_offset_ctrl',
    '18_cnr_ctrl',
    '19_tp_overlay_ctrl',
    '20_orientation_height_ctrl',
    '21_tp_multiplicity_ctrl',
    '22_tests_selection_ctrl',
    '90_plot_button_ctrl',
    '99_read_record',
    '91_run_tests_button_ctrl',
]